version: '2'
services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  nginx_proxy_local:
    image: cfoskin/nginx-proxy-local
    container_name: nginx-proxy-local
    ports:
      - "3000:8080"
      
  lead_service:
    image: cfoskin/lead-service
    container_name: lead-service
    depends_on:
      - "mongo"
    environment:
      - LOGGLY_TOKEN=$LOGGLY_TOKEN

  sales_agent_service:
    image: cfoskin/sales-agent-service
    container_name: sales-agent-service
    depends_on:
      - "mongo"
    environment:
      - LOGGLY_TOKEN=$LOGGLY_TOKEN

  push_configuraton_service:
    image: cfoskin/push-configuraton-service
    container_name: push-configuraton-service
    depends_on:
      - "mongo"
    environment:
      - LOGGLY_TOKEN=$LOGGLY_TOKEN

  aerodoc_client:
    image: cfoskin/aerodoc-client
    container_name: aerodoc-client 
    ports:
      - "8080:8080"